# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='doushidsb', max_length=32),
        ),
    ]
